apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: aws-node-template
spec:
  amiSelectorTerms:
    - alias: al2023@latest
  role: ${node_role}
  securityGroupSelectorTerms:
  - tags:
      Name: ${cluster_name}-node
      kubernetes.io/cluster/${cluster_name}: owned
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery/${cluster_name_prefix}: '*'
  tags:
    Name: Karpenter-Node
    karpenter.sh/discovery: ${cluster_name}
  metadataOptions:
    httpPutResponseHopLimit: 2
