apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace.name }}
  name: {{ .Values.deployment.name }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "1"
spec:
  {{- if and (not .Values.hpa.enabled) (not .Values.keda.enabled) }}
  replicas: {{ .Values.deployment.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.app.name }}
      {{- if .Values.opentelemetry.enabled }}
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
      {{- end }}
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: {{ .Values.app.name }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.container.port }}
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"
          env:
            - name: PROFILE
              valueFrom:
                configMapKeyRef:
                  key: environment
                  name: {{ .Values.configmap.name }}
            - name: JAVA_OPTIONS
              value: "-Dspring.profiles.active=${SPRING_PROFILES_ACTIVE}"
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  key: environment
                  name: {{ .Values.configmap.name }}
            - name: CODEBUILD_BUILD_NUMBER
              value: "{{ .Values.app.build_number }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-ui
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger-ui
  template:
    metadata:
      labels:
        app: swagger-ui
    spec:
      containers:
        - name: swagger-ui
          image: swaggerapi/swagger-ui
          ports:
            - containerPort: 8080
          env:
            - name: SWAGGER_JSON
              value: /tmp/openapi3.json
            - name: BASE_URL
              value: "/swagger-ui"
          volumeMounts:
            - name: swagger-config
              mountPath: /tmp
      volumes:
        - name: swagger-config
          configMap:
            name: swagger-config
            items:
              - key: openapi3.json
                path: openapi3.json
