{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace.name }}
  # {{- if .Values.hpa.enabled }}
  # annotations:
  #   scaledobject.keda.sh/transfer-hpa-ownership: "true"
  # {{- end }}
  # (IMPORTANT): Uncomment the following when you need to scale-in the pods to 0 for moeney saving.
{{/*  annotations:*/}}
{{/*    autoscaling.keda.sh/paused-replicas: "0"*/}}
{{/*    autoscaling.keda.sh/paused: "false"*/}}
spec:
  # {{- if .Values.hpa.enabled }}
  # advanced:
  #   horizontalPodAutoscalerConfig:
  #     name: {{ .Values.app.name }}
  # {{- end }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.deployment.name }}
  minReplicaCount: {{ .Values.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  triggers:
    # {{- if not .Values.hpa.enabled }}
    - type: cpu
      metricType: Utilization
      metadata:
        value: "30"
    # {{- end }}
  {{- end }}
