apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry-collector
  namespace: ${namespace}
spec:
  mode: deployment # This configuration is omittable.
  config:
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    processors:
    exporters:
      otlp/jaeger: # Jaeger supports OTLP directly. The default port for OTLP/gRPC is 4317
#        endpoint: "jaeger-collector.observability:14250"
        endpoint: "jaeger-collector.observability:4317"
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: []
          exporters: [otlp/jaeger]
