apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry-collector
  namespace: ${namespace}
spec:
  mode: deployment # This configuration is omittable.
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
            cors:
              allowed_origins:
                - http://*
                - https://*
      prometheus/otelcol:
        config:
          scrape_configs:
            - job_name: otel-collector-metrics
              scrape_interval: 10s
              static_configs:
                - targets: ['localhost:8888']
    processors:
    exporters:
      debug: {}
      logging:
        loglevel: debug
      otlp/jaeger: # Jaeger supports OTLP directly. The default port for OTLP/gRPC is 4317
        endpoint: "jaeger-collector.observability:4317"
        tls:
          insecure: true
      otlphttp/prometheus:
        endpoint: http://prometheus-kube-prometheus-prometheus.istio-system:9090/api/v1/otlp
        tls:
          insecure: true
      # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/connector/spanmetricsconnector
      prometheusremotewrite:
        # TODO: The Prometheus endpoint to send the metrics to.
        endpoint: http://prometheus-kube-prometheus-prometheus.istio-system:9090/api/v1/write
        tls:
          insecure: true
        target_info:
          enabled: true
      otlp/tempo:
        endpoint: tempo.grafana:4317
        tls:
          insecure: true

    connectors:
      spanmetrics:
        histogram:
          explicit:
            buckets: [100us, 1ms, 2ms, 6ms, 10ms, 100ms, 250ms, 500ms, 1s, 2s, 5s, 10s, 30s, 1m, 2m, 5m]
        dimensions:
          - name: http.method
            default: GET
          - name: http.status_code
        exemplars:
          enabled: true
        exclude_dimensions: ['status.code']
        dimensions_cache_size: 1000
        aggregation_temporality: "AGGREGATION_TEMPORALITY_CUMULATIVE"
        metrics_flush_interval: 15s
        metrics_expiration: 0
        events:
         enabled: true
         dimensions:
           - name: exception.type
           - name: exception.message
        resource_metrics_key_attributes:
          - service.name
          - telemetry.sdk.language
          - telemetry.sdk.name
    service:
      extensions: [zpages]
      pipelines:
        logs:
          receivers: [otlp]
          exporters: [debug]
        traces:
          receivers: [otlp]
          processors: []
          exporters: [otlp/jaeger, otlp/tempo, spanmetrics]
        metrics:
          receivers: [spanmetrics, prometheus/otelcol]
          exporters: [otlphttp/prometheus, logging, debug]
      telemetry:
        logs:
          level: "debug"
          development: true
          encoding: "console"
        metrics:
          level: "detailed"
          address: "0.0.0.0:8888"
    extensions:
      zpages:
        endpoint: 0.0.0.0:55679
