{
 "title": "(Large Memory Java) JVM Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "(LMJ) JVM Memory Pool Bytes Committed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_bytes_committed{instance=\"hotelspecials-service.hotelspecials.svc.cluster.local:9404\",job=\"hotelspecials-jmx\"})",
     "legendFormat": "${metric} (average)"
    }
   ]
  },
  {
   "title": "(LMJ) Memory Bytes Committed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_committed{instance=\"hotelspecials-service.hotelspecials.svc.cluster.local:9404\",job=\"hotelspecials-jmx\",area=\"heap\"}",
     "legendFormat": "${metric} (average)"
    }
   ]
  },
  {
   "title": "(LMJ) JVM Memory Bytes Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=\"hotelspecials-service.hotelspecials.svc.cluster.local:9404\",job=\"hotelspecials-jmx\"}",
     "legendFormat": "${metric} (average)"
    }
   ]
  }
 ]
}