{
 "title": "Karpenter Capacity v1 with Larage Memory Java JVM Metrics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "nodepool",
    "query": {
     "query": "label_values(karpenter_nodes_allocatable, nodepool)"
    }
   },
   {
    "name": "zone",
    "query": {
     "query": "label_values(karpenter_nodes_allocatable, zone)"
    }
   },
   {
    "name": "arch",
    "query": {
     "query": "label_values(karpenter_nodes_allocatable, arch)"
    }
   },
   {
    "name": "capacity_type",
    "query": {
     "query": "label_values(karpenter_nodes_allocatable, capacity_type)"
    }
   },
   {
    "name": "instance_type",
    "query": {
     "query": "label_values(karpenter_nodes_allocatable, instance_type)"
    }
   },
   {
    "name": "distribution_filter",
    "query": "arch,capacity_type,instance_type,namespace,node,nodepool,zone"
   }
  ]
 },
 "panels": [
  { "title": "Node Summary", "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "(LMJ) JVM Memory Pool Bytes Committed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_bytes_committed{instance=\"hotelspecials-service.hotelspecials.svc.cluster.local:9404\",job=\"hotelspecials-jmx\"})",
     "legendFormat": "${metric} (average)"
    }
   ]
  },
  {
   "title": "Nodes Created by nodepool",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(karpenter_nodes_created_total{nodepool=~\"$nodepool\"}[$__rate_interval])) by(cluster,nodepool)",
     "legendFormat": "{{cluster}}"
    },
    {
     "expr": "sum by(cluster,nodepool) (karpenter_nodes_created_total{nodepool=~\"$nodepool\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes Terminated by nodepool",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(karpenter_nodes_terminated_total{nodepool=~\"$nodepool\"}[$__rate_interval])) by(cluster,nodepool)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(cluster,nodepool) (karpenter_nodes_terminated_total{nodepool=~\"$nodepool\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Nodes Eligibale for Disruptions by \"reason\"",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by(reason)(karpenter_voluntary_disruption_eligible_nodes)",
     "legendFormat": "reason={{reason}}"
    }
   ]
  },
  {
   "title": "Node Disruptions by \"$distribution_filter\"",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(rate(karpenter_nodeclaims_disrupted_total{nodepool=~\"$nodepool\"}[$__rate_interval])) by(cluster,nodepool)",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "sum by(cluster,nodepool)(karpenter_nodeclaims_disrupted_total{nodepool=~\"$nodepool\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Disruption Actions performed by \"type\" and \"decision\"",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(rate(karpenter_voluntary_disruption_decisions_total[$__rate_interval])) by(cluster,nodepool,consolidation_type,decision)",
     "legendFormat": "type={{consolidation_type}}, decision={{decision}}"
    }
   ]
  },
  {
   "title": "Pod Distribution by \"$distribution_filter\"",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum by ($distribution_filter)(\n    karpenter_pods_state{arch=~\"$arch\", capacity_type=~\"$capacity_type\", instance_type=~\"$instance_type\", nodepool=~\"$nodepool\"}\n)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Pod Phase",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum by(phase)(karpenter_pods_state)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Nodepool Summary",
   "type": "table",
   "gridPos": { "h": 11, "w": 18, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "karpenter_nodepool_usage{resource_type=\"cpu\"} / karpenter_nodepool_limit{resource_type=\"cpu\"}",
     "legendFormat": "CPU Limit Utilization"
    },
    {
     "expr": "count by (nodepool)(karpenter_nodes_allocatable{nodepool!=\"N/A\",resource_type=\"cpu\"}) # Selects a single resource type to get node count"
    },
    {
     "expr": "karpenter_nodepool_usage{resource_type=\"memory\"} / karpenter_nodepool_limit{resource_type=\"memory\"}",
     "legendFormat": "Memory Limit Utilization"
    },
    {
     "expr": "sum by (nodepool)(karpenter_nodes_allocatable{nodepool!=\"N/A\",resource_type=\"cpu\"})"
    },
    {
     "expr": "sum by (nodepool)(karpenter_nodes_allocatable{nodepool!=\"N/A\",resource_type=\"memory\"})"
    }
   ]
  },
  {
   "title": "Spot Node Percentage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(count(karpenter_nodes_allocatable{arch=~\"$arch\",capacity_type=\"spot\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\"}) or vector(0)) / count(karpenter_nodes_allocatable{arch=~\"$arch\",instance_type=~\"$instance_type\",nodepool=~\"$nodepool\",zone=~\"$zone\"})",
     "legendFormat": "Percentage"
    }
   ]
  }
 ]
}