apiVersion: apps/v1
kind: Deployment
{{/*apiVersion: argoproj.io/v1alpha1*/}}
{{/*kind: Rollout*/}}
metadata:
  namespace: {{ .Values.namespace.name }}
  name: {{ .Values.deployment.name }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "1"
spec:
  {{- if and (not .Values.hpa.enabled) (not .Values.keda.enabled) }}
  replicas: {{ .Values.deployment.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.app.name }}
      annotations:
        prometheus.io/port: "9404"
        prometheus.io/scrape: "true"
        {{- if .Values.opentelemetry.enabled }}
        instrumentation.opentelemetry.io/inject-java: "true"
        {{- end }}
    spec:
      topologySpreadConstraints:
        - maxSkew: 6
          topologyKey: "topology.kubernetes.io/zone"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: {{ .Values.app.name }}
      nodeSelector:
        billing: aws-proserve
        purpose: memory-intensive-system
      tolerations:
        - key: "{{ .Values.deployment.tolerationKey }}"
          operator: Equal
          value: "true"
          effect: NoSchedule
      serviceAccountName: {{ .Values.namespace.name }}-service-account
      volumes:
        - name: config-volume
          configMap:
            name: "xray-config"
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: {{ .Values.app.name }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.container.port }}
              protocol: TCP
{{/*          resources:*/}}
{{/*            requests:*/}}
{{/*              memory: "154Gi"*/}}
{{/*              cpu: "10000m"*/}}
{{/*            limits:*/}}
{{/*              memory: "154Gi"*/}}
{{/*              cpu: "15000m"*/}}
          resources:
            requests:
              memory: "{{ .Values.deployment.resources.requests.memory }}"
              cpu: "{{ .Values.deployment.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.deployment.resources.limits.memory }}"
              cpu: "{{ .Values.deployment.resources.limits.cpu }}"
          env:
            - name: PROFILE
              valueFrom:
                configMapKeyRef:
                  key: environment
                  name: {{ .Values.configmap.name }}
            - name: JAVA_OPTS
              value: "-Xms20480M -Xmx148480M -Djava.awt.headless=true -Dspring.profiles.active=${SPRING_PROFILES_ACTIVE}"
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  key: environment
                  name: {{ .Values.configmap.name }}
            - name: DATABASE_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  key: database_endpoint
                  name: {{ .Values.configmap.name }}
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  key: database_port
                  name: {{ .Values.configmap.name }}
            - name: DATABASE_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: database_username
                  name: {{ .Values.configmap.name }}
            - name: DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: database_password
                  name: {{ .Values.configmap.name }}
            - name: JDBC_CONNECTION_STRING
              value: "jdbc:mysql://${DATABASE_ENDPOINT}:${DATABASE_PORT}/travelbuddy?useSSL=false&autoReconnect=true"
            - name: JDBC_UID
              value: ${DATABASE_USERNAME}
            - name: JDBC_PWD
              value: ${DATABASE_PASSWORD}
            - name: TZ
              value: Asia/Seoul
        - name: xray-daemon
          image: amazon/aws-xray-daemon:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: xray-ingest
              containerPort: 2000
              protocol: UDP
            - name: xray-tcp
              containerPort: 2000
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "400m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          # Volume mount for X-Ray Configuration.
          volumeMounts:
            - name: config-volume
              mountPath: /aws/xray
              readOnly: true
---
# Configuration for AWS X-Ray daemon.
apiVersion: v1
kind: ConfigMap
metadata:
  name: xray-config
  namespace: {{ .Values.namespace.name }}
data:
  config.yaml: |-
    TotalBufferSizeMB: 24
    Socket:
      UDPAddress: "0.0.0.0:2000"
      TCPAddress: "0.0.0.0:2000"
    LocalMode: true
    Version: 2
    Logging:
      LogLevel: "debug"
