{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.namespace.name }}
  {{- if .Values.hpa.enabled }}
  annotations:
    scaledobject.keda.sh/transfer-hpa-ownership: "true"
  {{- end }}
spec:
  {{- if .Values.hpa.enabled }}
  advanced:
    horizontalPodAutoscalerConfig:
      name: {{ .Values.app.name }}
  {{- end }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.deployment.name }}
  minReplicaCount: {{ .Values.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  triggers:
    {{- if not .Values.hpa.enabled }}
    - type: cpu
      metricType: Utilization
      metadata:
        value: 30
    {{- end }}
    - type: cron
      metadata:
        timezone: Asia/Seoul
        # 2월은 윤달 여부에 상관없이 20일에 스케일링 시작 - 다음 달 1일 새벽 1시에 종료
        start: 0 1 20 2 *
        end: 0 4 1 * *
        desiredReplicas: "{{ .Values.keda.desiredReplicaCountAtPeek }}"
    - type: cron
      metadata:
        timezone: Asia/Seoul
        # 30일 달은 22일에 스케일링 시작 - 다음 달 1일 새벽 1시에 종료
        start: 0 1 22 4,6,9,11 *
        end: 0 4 1 * *
        desiredReplicas: "{{ .Values.keda.desiredReplicaCountAtPeek }}"
    - type: cron
      metadata:
        timezone: Asia/Seoul
        # 31일 달은 23일 새벽 1시에 스케일링 시작 - 다음 달 1일 새벽 1시에 종료
        start: 0 1 23 1,3,5,7,8,10,12 *
        end: 0 4 1 * *
        desiredReplicas: "{{ .Values.keda.desiredReplicaCountAtPeek }}"
  {{- end }}
