apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace.name }}
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
      name: {{ .Values.service.name }}
    - port: 9000
      targetPort: 9000
      protocol: TCP
      name: jmx
    - port: 9404
      targetPort: 9404
      protocol: TCP
      name: prometheus-exporter
  selector:
    app.kubernetes.io/name: {{ .Values.app.name }}
  sessionAffinity: ClientIP
