# Istio VirtualService route rules are sometimes matched by creation timestamp.
# This is moved into the FlightSpecials application's VirtualService to ensure that the FlightSpecials application is matched first.
{{- if and (.Values.istio.enabled) (false) -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.app.name }}-virtualservice
  namespace: {{ .Values.namespace.name }}
spec:
  hosts:
    - "*"
  gateways:
    - {{ .Values.app.name }}-gateway
  http:
    - match:
        - uri:
            regex: /(.*)
      rewrite:
        uriRegexRewrite:
          match: /(.*)
          rewrite: /travelbuddy/\1
      route:
        - destination:
            host: {{ .Values.service.name }}
            port:
              number: {{ .Values.service.port }}
{{- end }}
