{{- if .Values.namespace.create -}}
kind: Namespace
apiVersion: v1
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    name: {{ .Values.namespace.name }}
    app: {{ .Values.app.name }}
    purpose: {{ .Values.app.purpose }}
    istio-injection: {{ .Values.istio.enabled }}
{{- end }}
