namespace:
  create: false
  name: flightspecials
app:
  name: flightspecials
  purpose: m2m
  build_number: 0
deployment:
  name: flightspecials
  replicas: 2
image:
  repository: ${ECR_REPO_URI}
  tag: ${IMAGE_TAG}
container:
  port: 8080
service:
  name: flightspecials-service
  type: NodePort
  port: 80
ingress:
  enabled: true
  name: flightspecials-ingress
  certificate_arn: ${CERTIFICATE_ARN}
istio:
  enabled: true
  ingressGatewayNamespace: istio-system
  ingressGatewayServiceName: istio-ingressgateway
  ingressGatewayServicePort: 80
configmap:
  name: flightspecials-configmap
  environment: test
  database_endpoint: ${DATABASE_ENDPOINT}
  database_port: ${DATABASE_PORT}
  database_username: ${DATABASE_USERNAME}
hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 30
keda:
  enabled: true
  minReplicaCount: 2
  maxReplicaCount: 4
  desiredReplicaCountAtPeak: 4
opentelemetry:
  enabled: true
  otlp_endpoint: "http://opentelemetry-collector-collector.opentelemetry.svc.cluster.local:4317"
  auto_instrumentation_sampling_rate: "1"
