{
 "title": "(Large Memory Java) JVM Metrics (v2)",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "(LMJ) JVM Memory Pool Bytes Committed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_pool_bytes_committed{job=\"insurance-planning-jmx\"})",
     "legendFormat": "JVM 메모리 풀 (합계, GB)"
    }
   ]
  },
  {
   "title": "(LMJ) JVM Memory Bytes Committed (Heap)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_committed{job=\"insurance-planning-jmx\",area=\"heap\"})",
     "legendFormat": "JVM 힙 메모리 할당 (합계)"
    }
   ]
  },
  {
   "title": "(LMJ) JVM Memory Bytes Used (Heap)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"insurance-planning-jmx\",area=\"heap\"}",
     "legendFormat": "JVM 힙 메모리 사용 ({{instance}})"
    }
   ]
  }
 ]
}