namespace:
  crate: false
  name: insurance
app:
  name: insurance-planning
  build_number: 0
deployment:
  name: insurance-planning
  replicas: 6
image:
  repository: ${ECR_REPO_URI}
  tag: "${IMAGE_TAG}"
container:
  port: 8080
service:
  name: insurance-planning-service
  type: NodePort
  port: 80
ingress:
  enabled: true
  name: insurance-planning-ingress
  certificate_arn: ${CERTIFICATE_ARN}
configmap:
  name: insurance-planning-configmap
  environment: dev
  database_endpoint: ${DATABASE_ENDPOINT}
  database_port: ${DATABASE_PORT}
  database_username: ${DATABASE_USERNAME}
  database_password: ${DATABASE_PASSWORD}
hpa:
  enabled: false
  minReplicas: 6
  maxReplicas: 24
  targetCPUUtilizationPercentage: 30
keda:
  enabled: true
  minReplicaCount: 6
  maxReplicaCount: 24
  desiredReplicaCountAtPeak: 24
opentelemetry:
  enabled: true
  otlp_endpoint: "http://opentelemetry-collector-collector.opentelemetry.svc.cluster.local:4317"
  auto_instrumentation_sampling_rate: "1"
