metricsGenerator:
  enabled: true
  config:
    storage:
      remote_write:
        - url: http://prometheus-kube-prometheus-prometheus.istio-system:9090/api/v1/write
          send_exemplars: true
traces:
  otlp:
    http:
      enabled: true
    grpc:
      enabled: true
global_overrides:
  metrics_generator_processors: [service-graphs, span-metrics]
#server:
#  logLevel: debug
